[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
master_of_the_epoch = "A7WpMwyorUkmTW9tvJLH48Xa4oiZ1ynvNqtWtdxtKChr"

[programs.mainnet]
master_of_the_epoch = "A7WpMwyorUkmTW9tvJLH48Xa4oiZ1ynvNqtWtdxtKChr"

[provider]
# X1 mainnet RPC — swap for localnet/devnet during testing
cluster = "https://xolana.xen.network"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
